spellchecker: aspell
matrix:
- name: python
  sources:
    - beginner_source/data_loading_tutorial.py
    - beginner_source/chatbot_tutorial.py
  dictionary:
    wordlists:
      - en-wordlist.txt
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # Exclude figure rST tags
        - open: '\.\.\s+(figure|literalinclude|)::'
          close: '\n'
        # Exclude Python coding directives
        - open: '-\*- coding:'
          close: '\n'
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      ignores:
        - code
        - pre
  - pyspelling.filters.url:
