spellchecker: aspell
matrix:
- name: python
  sources:
    - beginner_source/data_loading_tutorial.py
    - beginner_source/chatbot_tutorial.py
    - beginner_source/Intro_to_TorchScript_tutorial.py
    - beginner_source/dcgan_faces_tutorial.py
    - beginner_source/deploy_seq2seq_hybrid_frontend_tutorial.py
    - beginner_source/flava_finetuning_tutorial.py
  dictionary:
    wordlists:
      - en-wordlist.txt
  pipeline:
  - pyspelling.filters.python:
      group_comments: true
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # Exclude figure rST tags
        - open: '\.\.\s+(figure|literalinclude|math)::'
          close: '\n'
        # Exclude Python coding directives
        - open: '-\*- coding:'
          close: '\n'
        # Exclude Authors:
        - open: 'Author(|s):'
          close: '\n'
        # Exclude .rst directives:
        - open: ':math:`.*`'
          close: ' '
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      ignores:
        - code
        - pre
  - pyspelling.filters.url:
